version: '3.8'

services:
  php:
    build: './php'
    volumes:
      - ./app:/app:cached
      - ./php/monitoring.conf:/usr/local/etc/php-fpm.d/monitoring.conf:ro
    working_dir: /app
    depends_on:
      - mysql
      - elasticsearch
    links:
      - mysql
      - elasticsearch
    container_name: prjctr_php

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '127.0.0.1:${NGINX_PUBLIC_PORT}:80'
    volumes:
      - ./app:/app:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    links:
      - php
    container_name: prjctr_nginx

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - '127.0.0.1:${MYSQL_PUBLIC_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql:rw
    container_name: prjctr_mysql

  elasticsearch:
    image: elasticsearch:8.12.2
    env_file:
      - .env
    ports:
      - '127.0.0.1:${ELASTICSEARCH_PUBLIC_PORT}:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
    container_name: prjctr_elasticsearch

  telegraf:
    image: telegraf:1.29-alpine
    env_file:
      - .env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
      - php
      - nginx
      - mysql
      - elasticsearch
    container_name: prjctr_telegraf

  influxdb:
    image: influxdb:1.8-alpine
    env_file:
      - .env
    volumes:
      - influxdb_data:/var/lib/influxdb:rw
    container_name: prjctr_influxdb

  grafana:
    image: grafana/grafana-oss:10.4.0
    env_file:
      - .env
    ports:
      - '127.0.0.1:${GRAFANA_PUBLIC_PORT}:3000'
    volumes:
      - grafana_data:/var/lib/grafana:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - influxdb
    links:
      - influxdb
    container_name: prjctr_grafana

  apache:
    image: httpd:2.4-alpine
    links:
      - nginx
    container_name: prjctr_apache

volumes:
  mysql_data: {}
  elasticsearch_data: {}
  influxdb_data: {}
  grafana_data: {}
